version: '2'
services:
  consul:
    image: diogok/consul
    hostname: "consul"
    command: "-bootstrap"
    dns:
      - c
    environment:
      GOMAXPROCS: 4
    volumes:
      - ./:/opt/ops
    ports:
      - 8500:8500
      - 8600:53/udp
    networks:
      - consul
  mailer:
    image: diogok/smtp
    networks:
      - consul
  alerts:
    image: acaleph/consul-alerts
    command: "start --consul-addr=consul:8500 --watch-events --watch-checks --log-level=info"
    networks:
      - consul
  setup:
    image: tutum/curl
    working_dir: "/opt/ops"
    environment:
      URL: "http://consul:8500"
    volumes:
      - ./:/opt/ops
    command: "./setup.sh"
    networks:
      - consul
networks:
  consul:
