global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'services'
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,prometheus,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_tags]
        regex: .*,prometheus.metrics_path=([^,]+),.*
        replacement: '${1}'
        target_label: __metrics_path__
