FROM debian:stretch-slim

RUN apt-get update && apt-get install -yq tar curl git gettext-base

RUN curl "https://github.com/mholt/caddy/releases/download/v1.0.0/caddy_v1.0.0_linux_amd64.tar.gz" -L -o caddy.tar.gz && \
    tar --no-same-owner -C /usr/bin/ -xf caddy.tar.gz && rm caddy.tar.gz

EXPOSE 80
EXPOSE 443

CMD ["caddy", "--conf", "/etc/Caddyfile"]

#COPY Caddyfile /etc/Caddyfile

RUN echo ':80' > /etc/Caddyfile
RUN echo 'proxy / {$PROXY}' >> /etc/Caddyfile

