FROM fluent/fluent-bit:1.1.2

CMD ["/fluent-bit/bin/fluent-bit","--config","/fluent-bit/etc/fluent.cfg"]

ADD fluent.cfg /fluent-bit/etc/fluent.cfg

ENV LOKI_HOST loki
ENV LOKI_PORT 3100

ADD loki.cfg /fluent-bit/etc/output.cfg

