version: "2"
services:
  fluent:
    build: .
    image: diogok/fluentbit
    environment:
      ES_HOST: elasticsearch-logs
    ports:
      - 9514:9514/udp
      - 5432:5432/udp
      - 9600:9600

  kibana-logs:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-logs:9200

  elasticsearch-logs:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
    volumes:
      - /usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-elk
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "discovery.zen.ping.unicast.hosts=elasticsearch-logs"
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
